#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/src/helpers.php';

use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new \Docker\Commands\GenerateCommand());

$application->run();
