#!/usr/bin/env bash
CMD=$1
COMPOSE_FILE=./var/docker-compose.yml

function laradock_init_files() {
	OPTIONS=$1
	cp $OPTIONS resources/config.example.yml config.yml
	cp $OPTIONS resources/env.example .env
	cp $OPTIONS resources/my.example.cnf etc/my.cnf
	cp $OPTIONS resources/xdebug.example.ini etc/xdebug.ini
}

function laradock_generate() {
	docker run --rm -ti -v $PWD:/laradock -w /laradock php:7.2 php src/generate.php
}

function laradock_composer_install() {
	docker run --rm --interactive --tty \
		-v $PWD:/app \
		composer install --no-dev --no-progress --no-suggest
}

function laradock_compose() {
	docker-compose -f $COMPOSE_FILE --project-directory . ${@}
}

function laradock_info() {
	docker run --rm -ti -v $PWD:/laradock -w /laradock php:7.2 php src/info.php
}

if [[ $CMD == "init" ]]; then
	laradock_composer_install
	laradock_init_files "-i"
	echo "Laradock initialized!"
fi

if [[ $CMD == "up" ]]; then
	laradock_generate
	laradock_compose up -d --remove-orphans ${@:2}
	laradock_info
fi

if [[ $CMD == "info" ]]; then
	laradock_info
fi

if [[ $CMD == "ssh" ]]; then
	laradock_compose exec -u laradock workspace $(cat ./var/shell)
fi

if [[ $CMD == "root" ]]; then
	laradock_compose exec -u root workspace bash
fi

if [[ $CMD == "down" ]]; then
	laradock_compose down ${@:2}
fi

if [[ $CMD == "ps" ]]; then
	laradock_compose ps ${@:2}
fi

if [[ $CMD == "logs" ]]; then
	laradock_compose logs ${@:2}
fi

if [[ $CMD == "exec" ]]; then
	laradock_compose exec ${@:2}
fi

if [[ $CMD == "restart" ]]; then
	laradock_compose restart ${@:2}
fi

if [[ $CMD == "rebuild" ]]; then
	laradock_generate
	laradock_compose build --pull --force-rm
	laradock_compose up -d --remove-orphans
fi

if [[ $CMD == "upgrade" ]]; then
	git fetch
	git reset --hard origin/master
	# copy example config files that are missed only
	# existing ones will be preserved
	laradock_init_files "-n"
	laradock_composer_install
	./laradock rebuild
	echo "Laradock upgraded!"
fi
